try:
    import cPickle as pickle
except ImportError:  # Python 3.x
    import pickle
import os
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from assessment_functions import *

def main():
    mainpath = "/provSpark-datasets"
    # load results of accuracy document generated by train.py
    with open(mainpath+'/'+'final_res.p', 'rb') as fp:
        dictsaved = pickle.load(fp)
    datasets_dir = os.listdir(mainpath)
    datasets_NP = [name + "NP.orc" for name in datasets_dir]
    datasets_P =  [name + "P.orc" for name in datasets_dir]


    #separate results of pk-np and pk-p
    NP = dictsaved[0]
    P = dictsaved[1]
    datasetDict = {}
    #remove the layer of dictionary with "accuracy" as key to directly fits the results into a pandas dataframe
    for dataset in NP.keys():
      acc = NP[dataset]["Accuracy"]
      datasetDict[dataset] = acc


    dftest = pd.DataFrame(datasetDict).transpose()

    #plot out the results directly from the dataframe
    dftest.plot(kind="bar",figsize = (12,10))
    plt.xlabel("Datasets")
    plt.ylabel("Accuracy")
    plt.title("Classification accuracy over all PK-NP datasets")
    plt.savefig('/plots/experiement2.pdf')

if __name__ == "__main__":
    main()